//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kenedia.Modules.Characters.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kenedia.Modules.Characters.Strings.common", typeof(common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armorsmith.
        /// </summary>
        internal static string Armorsmith {
            get {
                return ResourceManager.GetString("Armorsmith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artificer.
        /// </summary>
        internal static string Artificer {
            get {
                return ResourceManager.GetString("Artificer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If enabled on the first load of Blish and beeing in character selection the module enters the game. After entering the game it will wait until the MumbleLink and API Token is fully loaded.
        ///Once fully loaded it will switch to the character which is set to be the &quot;Login Character&quot;..
        /// </summary>
        internal static string AutoLogin_Description {
            get {
                return ResourceManager.GetString("AutoLogin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Login to selected Character.
        /// </summary>
        internal static string AutoLogin_DisplayName {
            get {
                return ResourceManager.GetString("AutoLogin_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        internal static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chef.
        /// </summary>
        internal static string Chef {
            get {
                return ResourceManager.GetString("Chef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crafting Profession.
        /// </summary>
        internal static string CraftingProfession {
            get {
                return ResourceManager.GetString("CraftingProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Tags.
        /// </summary>
        internal static string CustomTags {
            get {
                return ResourceManager.GetString("CustomTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables double clicking the character in the character list to login to that character..
        /// </summary>
        internal static string DoubleClickToEnter_Description {
            get {
                return ResourceManager.GetString("DoubleClickToEnter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Click to Swap.
        /// </summary>
        internal static string DoubleClickToEnter_DisplayName {
            get {
                return ResourceManager.GetString("DoubleClickToEnter_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the game automatically after selecting the character in the character selection.
        /// </summary>
        internal static string EnterOnSwap_Description {
            get {
                return ResourceManager.GetString("EnterOnSwap_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login after selecting the character.
        /// </summary>
        internal static string EnterOnSwap_DisplayName {
            get {
                return ResourceManager.GetString("EnterOnSwap_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character swapping is disabled in competition mode!.
        /// </summary>
        internal static string Error_Competivive {
            get {
                return ResourceManager.GetString("Error_Competivive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This API key does not have the required permissions..
        /// </summary>
        internal static string Error_InvalidPermissions {
            get {
                return ResourceManager.GetString("Error_InvalidPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average time in milliseconds waited between filtering your characters&apos; panel.
        ///To get the current value you will have to swap module tabs once to update the settings page!.
        /// </summary>
        internal static string FilterDelay_Description {
            get {
                return ResourceManager.GetString("FilterDelay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Delay ({0} ms).
        /// </summary>
        internal static string FilterDelay_DisplayName {
            get {
                return ResourceManager.GetString("FilterDelay_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huntsman.
        /// </summary>
        internal static string Huntsman {
            get {
                return ResourceManager.GetString("Huntsman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeweler.
        /// </summary>
        internal static string Jeweler {
            get {
                return ResourceManager.GetString("Jeweler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leatherworker.
        /// </summary>
        internal static string Leatherworker {
            get {
                return ResourceManager.GetString("Leatherworker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0}.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the game automatically after selecting the character in the character selection.
        /// </summary>
        internal static string LoginAfterSelect {
            get {
                return ResourceManager.GetString("LoginAfterSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in character.
        /// </summary>
        internal static string LoginCharacter {
            get {
                return ResourceManager.GetString("LoginCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key to Press to open the logout menu. Must be the same as the game keybind for &apos;Logout&apos;!.
        /// </summary>
        internal static string LogoutDescription {
            get {
                return ResourceManager.GetString("LogoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tool to easily switch characters even with a lot of them!
        ///This will require an API-Key with permissions at least for the &apos;characters&apos; endpoint!.
        /// </summary>
        internal static string ModuleDescription {
            get {
                return ResourceManager.GetString("ModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Crafting Profession.
        /// </summary>
        internal static string NoCraftingProfession {
            get {
                return ResourceManager.GetString("NoCraftingProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        internal static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scribe.
        /// </summary>
        internal static string Scribe {
            get {
                return ResourceManager.GetString("Scribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for ....
        /// </summary>
        internal static string SearchFor {
            get {
                return ResourceManager.GetString("SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -c Crafting Profession
        ///-p Profession/Specialization
        ///-r Race
        ///-b Birthday
        ///-m MapName
        ///-t CustomTag
        ///-c Chef; -p Warrior will show all warriors and all chefs.
        /// </summary>
        internal static string SearchGuide {
            get {
                return ResourceManager.GetString("SearchGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key to Press to toggle the characters menu..
        /// </summary>
        internal static string ShortcutToggle_Description {
            get {
                return ResourceManager.GetString("ShortcutToggle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Menu.
        /// </summary>
        internal static string ShortcutToggle_DisplayName {
            get {
                return ResourceManager.GetString("ShortcutToggle_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        internal static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. loading time from ingame to character selection.
        ///To get the current value you will have to swap module tabs once to update the settings page!.
        /// </summary>
        internal static string SwapDelay_Description {
            get {
                return ResourceManager.GetString("SwapDelay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Delay ({0} ms).
        /// </summary>
        internal static string SwapDelay_DisplayName {
            get {
                return ResourceManager.GetString("SwapDelay_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to {0}.
        /// </summary>
        internal static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailor.
        /// </summary>
        internal static string Tailor {
            get {
                return ResourceManager.GetString("Tailor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle All.
        /// </summary>
        internal static string ToggleAll {
            get {
                return ResourceManager.GetString("ToggleAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide hidden Characters.
        /// </summary>
        internal static string ToggleVisible {
            get {
                return ResourceManager.GetString("ToggleVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkown.
        /// </summary>
        internal static string Unkown {
            get {
                return ResourceManager.GetString("Unkown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until Birthday.
        /// </summary>
        internal static string UntilBirthday {
            get {
                return ResourceManager.GetString("UntilBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update {0}.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated {0}.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0}.
        /// </summary>
        internal static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility.
        /// </summary>
        internal static string Utility {
            get {
                return ResourceManager.GetString("Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weaponsmith.
        /// </summary>
        internal static string Weaponsmith {
            get {
                return ResourceManager.GetString("Weaponsmith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
    }
}
